### ISSUE TITLE
TypeError: Can't instantiate abstract class Album with abstract methods __call__

### ISSUE THREAD

**Issue by gary360** [91DarioDev/forwardscoverbot#30]
When running forwardscoverbot/custom_filter its giving this error
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 25, in <module>
TypeError: Can't instantiate abstract class Album with abstract methods __call__

[Program finished]
```
Sorry if i left of any valuable information in the question

**Comment by devsdocs** [comment]
Got this error before, change the ptb version to 12.8, it will work

**Comment by gary360** [comment]
> Got this error before, change the ptb version to 12.8, it woll work

Oh thanks i will try it

**Comment by gary360** [comment]
> Got this error before, change the ptb version to 12.8, it woll work

Thanks man it worked 😊

**Comment by 91DarioDev** [comment]
Thank you! I just released support for ptb v13

**Comment by zotor** [comment]
Same error with python-telegram-bot 13.4.1
TypeError: Can't instantiate abstract class Album with abstract method __call__

My package :

aiohttp==3.7.4.post0
APScheduler==3.6.3
async-timeout==3.0.1
attrs==20.3.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cryptg==0.2.post2
cryptography==3.4.6
forwardscoverbot==1
idna==3.1
multidict==5.1.0
pycparser==2.20
python-telegram-bot==13.4.1
pytz==2021.1
PyYAML==5.4.1
six==1.15.0
tornado==6.1
typing-extensions==3.7.4.3
tzlocal==2.1
yarl==1.6.3

**Comment by 91DarioDev** [comment]
> Same error with python-telegram-bot 13.4.1
> TypeError: Can't instantiate abstract class Album with abstract method **call**
> 
> My package :
> 
> aiohttp==3.7.4.post0
> APScheduler==3.6.3
> async-timeout==3.0.1
> attrs==20.3.0
> certifi==2020.12.5
> cffi==1.14.5
> chardet==4.0.0
> cryptg==0.2.post2
> cryptography==3.4.6
> forwardscoverbot==1
> idna==3.1
> multidict==5.1.0
> pycparser==2.20
> python-telegram-bot==13.4.1
> pytz==2021.1
> PyYAML==5.4.1
> six==1.15.0
> tornado==6.1
> typing-extensions==3.7.4.3
> tzlocal==2.1
> yarl==1.6.3

The bug you referred was opened because they were using python-telegram-bot 13 but my code was written for version 12.
After that I supported v13 changing the code and it worked. I tried to test on my environment v13.4.1 and it works fine.

Which python version are you using? Also it sound like if you are using a version before 13 of the python-telegram-bot dependency 🤔

**Comment by Mwoodin12** [comment]
Congratulations
