### ISSUE TITLE
How to make it work in groups?

### ISSUE THREAD

**Issue by gary360** [91DarioDev/forwardscoverbot#34]
The bot leaves soon after i added it to the group.
Is there any way to make it work on groups.

**Comment by 91DarioDev** [comment]
The bot has not developed to work in groups and the fact that it leaves the group is intended. 

I think that if you want to make it work in groups, you should fork it, comment the part where it leaves groups and add handle groups json update if needed

**Comment by gary360** [comment]
Ok
