### ISSUE TITLE
It also echoing commands

### ISSUE THREAD

**Issue by mendisofficial** [91DarioDev/forwardscoverbot#39]
When I gives a command (/start) it gives the start message and also echo the /start command. How to fix that?

**Comment by 91DarioDev** [comment]
It is intended, otherwise if you want to echo /start you can’t

**Comment by 91DarioDev** [comment]
If you don’t want this, you should change __main__.py and add this message handler filter 
dp.add_handler(MessageHandler(Filters.all, messages.process_message, run_async=True), 1)
after all the commands handlers 
Also they should have the same group handler index, so replace 1 with 2

**Comment by mendisofficial** [comment]
Thanks for the info
