### ISSUE TITLE
Check It 

### ISSUE THREAD

**Issue by k1tx101** [91DarioDev/forwardscoverbot#47]

**Comment by Kr1ts4d4XR** [comment]
C:\xxxxx\xxxxxx\xxxxx\forwardscoverbot-master>pip install .
Processing c:\users\kritsada\downloads\forwardscoverbot-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-telegram-bot==20.0 (from forwardscoverbot==1)
  Using cached python_telegram_bot-20.0-py3-none-any.whl (484 kB)
Requirement already satisfied: Pyyaml in c:\python310\lib\site-packages (from forwardscoverbot==1) (6.0)
Requirement already satisfied: aiosqlite in c:\python310\lib\site-packages (from forwardscoverbot==1) (0.18.0)
Requirement already satisfied: httpx~=0.23.1 in c:\python310\lib\site-packages (from python-telegram-bot==20.0->forwardscoverbot==1) (0.23.3)
Requirement already satisfied: certifi in c:\python310\lib\site-packages (from httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (2022.12.7)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\python310\lib\site-packages (from httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\python310\lib\site-packages (from httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (1.5.0)
Requirement already satisfied: sniffio in c:\python310\lib\site-packages (from httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\python310\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\python310\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (3.6.2)
Requirement already satisfied: idna in c:\python310\lib\site-packages (from rfc3986[idna2008]<2,>=1.3->httpx~=0.23.1->python-telegram-bot==20.0->forwardscoverbot==1) (3.4)
Building wheels for collected packages: forwardscoverbot
  Building wheel for forwardscoverbot (pyproject.toml) ... done
  Created wheel for forwardscoverbot: filename=forwardscoverbot-1-py3-none-any.whl size=27368 sha256=406c12e8b947ec482c43d3a665477f94d311bb02c567095efd2508780833ced2
  Stored in directory: c:\users\kritsada\appdata\local\pip\cache\wheels\15\df\e6\a21d3960f1336e602e4ab09c930eec4a9c2dab56fd42102471
Successfully built forwardscoverbot
Installing collected packages: python-telegram-bot, forwardscoverbot
  Attempting uninstall: python-telegram-bot
    Found existing installation: python-telegram-bot 20.2
    Uninstalling python-telegram-bot-20.2:
      Successfully uninstalled python-telegram-bot-20.2
  Attempting uninstall: forwardscoverbot
    Found existing installation: forwardscoverbot 1
    Uninstalling forwardscoverbot-1:
      Successfully uninstalled forwardscoverbot-1
Successfully installed forwardscoverbot-1 python-telegram-bot-20.0
